org:
  #should be overridden with env
  neo4j:
    driver.uri: ${NEO4J_URI:bolt://localhost:7687}
    driver:
      authentication:
        username: ${NEO4J_USERNAME:neo4j}
        password: ${NEO4J_PASSWORD:neo4j}